### ISSUE TITLE
Issues with DUNGEON.jcl

### ISSUE THREAD

**Issue by lnlyssg** [mainframed/CICS_Dungeon#1]
I'm using the normal KICKS docker image and after issuing 'cat DUNGEON.jcl|ncat localhost 3505' I can see the DNGN job is failing because of a missing STEPLIB, it seems I have no GCC or PDPCLIB datasets cataloged so the compile fails due to missing datasets. I can see they are on the SYSCPK volume but they don't appear to be cataloged in the Docker image. After cataloging them the job got further but now fails with `$HASP165 JOB   49  DNGN ENDED- ABENDED  SYSTEM 806`

``` 
IEA703I 806- 4 DNGN     COMP     MODULE ACCESSED GCC370            
IEF472I DNGN COMP DEATHPGM - COMPLETION CODE - SYSTEM=806 USER=0000
```

I'm still trying to work this one out so any ideas would be helpful!

**Comment by NoOne60** [comment]
Hello,
while waiting for a response from the repository owner, I can say that the cataloged procedures found in KICKS.KICKSSYS.V1R5M0.PROCLIB are designed for a different distribution and are ill-suited to being moved as they are from one place to another.
I can say that the error is caused by one of these procedures which tries to call the compiler with the name of GCC370 while in GCC.LINKLIB on the SYSCPK volume it is called GCC, therefore the error 806 which is generic for "can not find something."

I don't think that what I have written is enough to achieve the desired result, but it is certainly a first step

**Comment by lnlyssg** [comment]
Cheers @NoOne60, I know z/OS well and suspected it was a missing program but I'm not very familiar with MVS 3.8 so I've struggled to find my way around!

**Comment by NoOne60** [comment]
Oh, I understand.,, get on board your time machine and have a good trip!

**Comment by mainframed** [comment]
> I'm using the normal KICKS docker image and after issuing 'cat DUNGEON.jcl|ncat localhost 3505' I can see the DNGN job is failing because of a missing STEPLIB, it seems I have no GCC or PDPCLIB datasets cataloged so the compile fails due to missing datasets. I can see they are on the SYSCPK volume but they don't appear to be cataloged in the Docker image. After cataloging them the job got further but now fails with `$HASP165 JOB 49 DNGN ENDED- ABENDED SYSTEM 806`
> 
> ```
> IEA703I 806- 4 DNGN     COMP     MODULE ACCESSED GCC370            
> IEF472I DNGN COMP DEATHPGM - COMPLETION CODE - SYSTEM=806 USER=0000
> ```
> 
> I'm still trying to work this one out so any ideas would be helpful!

This is because theres no `GCC370` in `GCC.LINKLIB` (an oversight by me making the container). Until I have time to fix the container you can use `RENAME 'GCC.LINKLIB(GCC)' 'GCC.LINKLIB(GCC370)' ALIAS`. Also, make sure you pull the latest version, there was another bug in the JCL that I fixed this morning.
